# Generated by Django 3.0.6 on 2020-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='date',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='time_required',
            field=models.CharField(default='', max_length=40),
        ),
    ]
