# Generated by Django 3.0.6 on 2020-05-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200506_0506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsItem',
            new_name='Recipe',
        ),
    ]
